### ISSUE TITLE
MissionBriefingAction conversion for action `8` is wrong (and `9` is missing)

### ISSUE THREAD

**Issue by tec27** [zzlk/bwmap#3]
https://github.com/zzlk/bwmap/blob/109b41c9f1675293f745d6391ecef5df5d015a0e/src/trig.rs#L1644-L1646

Seems like you forgot `Transmission` and parsed any of those actions as `SkipTutorialEnabled` instead

**Comment by zzlk** [comment]
Thank you for finding this, I'll fix it shortly.

**Comment by zzlk** [comment]
fixed in: e02c546, sorry it took so long, I was moving :)
